################################################################################################################
# The default configuration values for Vinyl
################################################################################################################
vinyldns {

  api {
      limits {
        batchchange-routing-max-items-limit = 100
        membership-routing-default-max-items = 100
        membership-routing-max-items-limit = 1000
        membership-routing-max-groups-list-limit = 1500
        recordset-routing-default-max-items = 100
        zone-routing-default-max-items = 100
        zone-routing-max-items-limit = 100
      }
    }

  valid-email-config {
    email-domains  = ["test.com","*dummy.com"]
    number-of-dots = 2
  }

  backend {
      default-backend-id = "default"
      backend-providers: [{
        "class-name": "vinyldns.api.backend.dns.DnsBackendProviderLoader",
        "settings": {
          "legacy": false,
          backends = [
              {
                id = "default"
                zone-connection = {
                  name = "vinyldns."
                  key-name = "vinyldns."
                  key = "nzisn+4G2ldMn0q1CV3vsg=="
                  primary-server = "127.0.0.1:19001"
                }
                transfer-connection = {
                  name = "vinyldns."
                  key-name = "vinyldns."
                  key = "nzisn+4G2ldMn0q1CV3vsg=="
                  primary-server = "127.0.0.1:19001"
                },
                tsig-usage = "always"
              },
              {
                id = "func-test-backend"
                zone-connection = {
                  name = "vinyldns."
                  key-name = "vinyldns."
                  key = "nzisn+4G2ldMn0q1CV3vsg=="
                  primary-server = "127.0.0.1:19001"
                }
                transfer-connection = {
                  name = "vinyldns."
                  key-name = "vinyldns."
                  key = "nzisn+4G2ldMn0q1CV3vsg=="
                  primary-server = "127.0.0.1:19001"
                },
                tsig-usage = "always"
              }
            ]
        }
      }]
  }

  dotted-hosts = {
    allowed-settings = [
      {
      # for wildcard zones. Settings will be applied to all matching zones
      zone = "*ent.com*."
      user-list = ["ok"]
      group-list = ["dummy-group"]
      record-types = ["CNAME"]
      dots-limit = 3
      },
      {
      # for wildcard zones. Settings will be applied to all matching zones
      zone = "dummy*."
      user-list = ["sharedZoneUser"]
      group-list = ["history-group1"]
      record-types = ["A"]
      dots-limit = 3
      }
    ]
  }
  queue {
      max-retries       = 100
      messages-per-poll = 10
      polling-interval  = 250.millis
  }

  # These configs are not refers the application at startup. It needed for tests.
  manual-batch-review-enabled = true
  shared-approved-types = ["A", "AAAA", "CNAME", "PTR", "TXT"]
  default-ttl = 7200
  max-zone-size = 60000
  sync-delay = 600000
  approved-name-servers = [
      "172.17.42.1.",
      "ns1.parent.com."
    ]
  load-test-data = false
  load-test-data = ${?LOAD_TEST_DATA}
  is-zone-sync-schedule-allowed = true
  is-zone-sync-schedule-allowed = ${?IS_ZONE_SYNC_SCHEDULE_ALLOWED}
  processing-disabled = false
  batch-change-limit = 1000
  scheduled-changes-enabled = false
  multi-record-batch-change-enabled = true
  use-recordset-cache = false
  use-recordset-cache = ${?USE_RECORDSET_CACHE}
  validate-record-lookup-against-dns-backend = false
  high-value-domains = {
    fqdn-regex-list = []
    ip-list = []
  }
  manual-review-domains = {
    domain-list = []
    ip-list = []
    zone-name-list = []
  }
  global-acl-rules = []
}