version: "3.0"
services:
  mysql:
    image: "mysql:5.7"
    env_file:
      .env
    container_name: "vinyldns-mysql"
    ports:
    - "19002:3306"
    logging:
      driver: none

  bind9:
    image: "vinyldns/test-bind9:0.9.4"
    container_name: "vinyldns-bind9"
    ports:
    - "19001:53/tcp"
    - "19001:53/udp"
    logging:
      driver: none

  dynamodb-local:
    image: cnadiminti/dynamodb-local:2017-02-16
    container_name: "vinyldns-dynamodb"
    env_file:
      .env
    logging:
      driver: none
    ports:
    - "19000:8000"
    command: "--sharedDb --inMemory"

  localstack:
    image: localstack/localstack:0.10.4
    container_name: "vinyldns-localstack"
    ports:
      - "19000:19000"
      - "19006:19006"
      - "19007:19007"
      - "19009:19009"
    environment:
      - SERVICES=dynamodb:19000,sns:19006,sqs:19007,route53:19009
      - START_WEB=0
      - HOSTNAME_EXTERNAL=vinyldns-localstack

  # this file is copied into the target directory to get the jar!  won't run in place as is!
  api:
    build:
      context: api
    env_file:
      .env
    container_name: "vinyldns-api"
    ports:
    - "9000:9000"
    depends_on:
    - mysql
    - bind9
    - localstack
    logging:
      driver: none

  functest:
    build:
      context: functest
    env_file:
      .env
    environment:
    - PAR_CPU=${PAR_CPU}
    container_name: "vinyldns-functest"
    depends_on:
    - api
