version: "3.0"
services:
  mysql:
    image: "mysql:5.7"
    env_file:
      .env
    container_name: "vinyldns-mysql"
    ports:
      - "19002:3306"

  bind9:
    image: "vinyldns/bind9:0.0.4"
    env_file:
      .env
    container_name: "vinyldns-bind9"
    ports:
      - "19001:53/udp"
      - "19001:53"
    volumes:
      - ./bind9/etc:/var/cache/bind/config
      - ./bind9/zones:/var/cache/bind/zones

  localstack:
    image: localstack/localstack:0.10.4
    container_name: "vinyldns-localstack"
    ports:
      - "19000:19000"
      - "19006:19006"
      - "19007:19007"
    environment:
      - SERVICES=dynamodb:19000,sns:19006,sqs:19007
      - START_WEB=0
      - HOSTNAME_EXTERNAL=vinyldns-localstack

  ldap:
    image: rroemhild/test-openldap
    container_name: "vinyldns-ldap"
    ports:
      - "19008:389"

  api:
    image: "vinyldns/api:${VINYLDNS_VERSION}"
    env_file:
      .env
    container_name: "vinyldns-api"
    ports:
      - "${REST_PORT}:${REST_PORT}"
    volumes:
      - ./api/docker.conf:/opt/docker/conf/application.conf      
    depends_on:
      - mysql
      - bind9
      - localstack

  portal:
    image: "vinyldns/portal:${VINYLDNS_VERSION}"
    env_file:
      .env
    ports:
      - "${PORTAL_PORT}:${PORTAL_PORT}"
    container_name: "vinyldns-portal"
    volumes:
      - ./portal/application.ini:/opt/docker/conf/application.ini
      - ./portal/application.conf:/opt/docker/conf/application.conf
    depends_on:
      - api
      - ldap
