version: "3.0"
services:
  mysql:
    image: "mysql:5.7"
    container_name: "vinyldns-mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=pass # do not use quotes around the environment variables!!!
      - MYSQL_ROOT_HOST=% # this is required as mysql is currently locked down to localhost
    ports:
      - "3306:3306"

  dynamodb:
    image: "cnadiminti/dynamodb-local:2017-02-16"
    container_name: "vinyldns-dynamodb"
    ports:
      - "19000:8000"
    command: "--sharedDb --inMemory"

  bind9:
    image: "vinyldns/bind9:0.0.1"
    container_name: "vinyldns-bind9"
    ports:
      - "19001:53/udp"
      - "19001:53"
    volumes:
      - ./bind9/etc:/var/cache/bind/config
      - ./bind9/zones:/var/cache/bind/zones

  elasticmq:
    image: s12v/elasticmq:0.13.8
    container_name: "vinyldns-elasticmq"
    ports:
      - "9324:9324"
    volumes:
      - ./elasticmq/custom.conf:/etc/elasticmq/elasticmq.conf

  api:
    image: "vinyldns/api:0.1" # the version of the api image we want to pull
    environment:
      - REST_PORT=9000
    container_name: "vinyldns-api"
    ports:
      - "9000:9000"
    depends_on:
      - mysql
      - bind9
      - elasticmq
      - dynamodb

  portal:
    image: "vinyldns/portal:0.1" # the version of the portal image we want to pull
    ports:
      - "9001:9001"
    container_name: "vinyldns-portal"
    volumes:
      - ./portal/application.conf:/opt/docker/conf/application.conf
      - ./portal/application.ini:/opt/docker/conf/application.ini
    depends_on:
      - api
